import { TASA_Orbiter } from "next/font/google";
import { ViewTransitions } from "next-view-transitions";
import "./globals.css";

const geistSans = TASA_Orbiter({
  weight: '600',
  subsets: ["latin"],
});

const geistMono = TASA_Orbiter({
  weight: '400',
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ViewTransitions>
      <html
        lang="en"
        className="${geistSans.variable} ${geistMono.variable} h-full antialiased"
      >
        <body className="min-h-full flex flex-col">{children}</body>
      </html>
    </ViewTransitions>
  );
}
